// SPDX-License-Identifier: AGPL-3.0-or-later
//
// WS-S.4.2 — private CIDv1 tests.  The reference CIDs were generated with the
// `multiformats` library (the standard IPFS CID implementation), so the hand-
// rolled `computePrivateCid` is pinned byte-for-byte to a real CIDv1 codec; the
// base32 body is independently checked against RFC 4648 §10 vectors.
import { describe, expect, it } from 'vitest';
import {
  base32LowerNoPad,
  computePrivateCid,
  PRIVATE_CID_CODEC,
  verifyPrivateCid,
} from '../crypto/cid.js';
import { utf8 } from '../crypto/runtime.js';

// Generated by `multiformats` — CID.create(1, codec, sha256.digest(data)).
const REFERENCE = [
  {
    label: 'empty',
    data: new Uint8Array(0),
    raw: 'bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku',
    dagCbor: 'bafyreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku',
  },
  {
    label: 'hello',
    data: utf8('hello'),
    raw: 'bafkreibm6jg3ux5qumhcn2b3flc3tyu6dmlb4xa7u5bf44yegnrjhc4yeq',
    dagCbor: 'bafyreibm6jg3ux5qumhcn2b3flc3tyu6dmlb4xa7u5bf44yegnrjhc4yeq',
  },
  {
    label: 'ciphertext',
    data: utf8('encrypted-private-object'),
    raw: 'bafkreigc2sfrwwlybc2h7xj2rvbfe5adeg4dx2ieoikm2hyjvo2as3yaea',
    dagCbor: 'bafyreigc2sfrwwlybc2h7xj2rvbfe5adeg4dx2ieoikm2hyjvo2as3yaea',
  },
] as const;

describe('private CIDv1 (multiformats-pinned)', () => {
  for (const ref of REFERENCE) {
    it(`matches the multiformats raw (0x55) CID for ${ref.label}`, async () => {
      expect(await computePrivateCid(ref.data, PRIVATE_CID_CODEC.raw)).toBe(ref.raw);
    });
    it(`matches the multiformats dag-cbor (0x71) CID for ${ref.label}`, async () => {
      expect(await computePrivateCid(ref.data, PRIVATE_CID_CODEC.dagCbor)).toBe(ref.dagCbor);
    });
  }

  it('raw vs dag-cbor differ only by codec (same digest)', async () => {
    const data = utf8('same bytes');
    const raw = await computePrivateCid(data, PRIVATE_CID_CODEC.raw);
    const cbor = await computePrivateCid(data, PRIVATE_CID_CODEC.dagCbor);
    expect(raw).not.toBe(cbor);
    expect(raw.startsWith('bafkrei')).toBe(true); // raw 0x55
    expect(cbor.startsWith('bafyrei')).toBe(true); // dag-cbor 0x71
  });

  it('verifyPrivateCid round-trips and rejects a tampered ciphertext', async () => {
    const data = utf8('private op envelope ciphertext');
    const cid = await computePrivateCid(data, PRIVATE_CID_CODEC.raw);
    expect(await verifyPrivateCid(data, cid, PRIVATE_CID_CODEC.raw)).toBe(true);
    expect(await verifyPrivateCid(utf8('tampered'), cid, PRIVATE_CID_CODEC.raw)).toBe(false);
    // a CID is codec-bound: the same bytes under the wrong codec does not verify
    expect(await verifyPrivateCid(data, cid, PRIVATE_CID_CODEC.dagCbor)).toBe(false);
  });
});

describe('base32 (RFC 4648 §10, lowercase no-pad)', () => {
  it('matches the RFC 4648 test vectors', () => {
    expect(base32LowerNoPad(utf8(''))).toBe('');
    expect(base32LowerNoPad(utf8('f'))).toBe('my');
    expect(base32LowerNoPad(utf8('fo'))).toBe('mzxq');
    expect(base32LowerNoPad(utf8('foo'))).toBe('mzxw6');
    expect(base32LowerNoPad(utf8('foob'))).toBe('mzxw6yq');
    expect(base32LowerNoPad(utf8('fooba'))).toBe('mzxw6ytb');
    expect(base32LowerNoPad(utf8('foobar'))).toBe('mzxw6ytboi');
  });

  it('agrees with a BigInt reference at every length (no accumulator overflow)', () => {
    // An independent, obviously-correct encoder over a BigInt bit-stream — no
    // 32-bit accumulator, so it cannot share any truncation behavior with the
    // streaming encoder.  Agreement across lengths up to 40 bytes (well past the
    // 4-byte point where a 32-bit accumulator would overflow) pins the streaming
    // encoder's correctness independent of how many bits it happens to read.
    const reference = (bytes: Uint8Array): string => {
      if (bytes.length === 0) return '';
      let acc = 0n;
      for (const b of bytes) acc = (acc << 8n) | BigInt(b);
      const totalBits = bytes.length * 8;
      const outLen = Math.ceil(totalBits / 5);
      acc <<= BigInt(outLen * 5 - totalBits); // RFC 4648 zero-pads the low bits
      let out = '';
      for (let i = outLen - 1; i >= 0; i--) {
        out += BASE32_REFERENCE_ALPHABET[Number((acc >> BigInt(i * 5)) & 0x1fn)];
      }
      return out;
    };
    for (let len = 0; len <= 40; len++) {
      const bytes = new Uint8Array(len);
      for (let i = 0; i < len; i++) bytes[i] = (i * 37 + 11) & 0xff;
      expect(base32LowerNoPad(bytes)).toBe(reference(bytes));
    }
  });
});

const BASE32_REFERENCE_ALPHABET = 'abcdefghijklmnopqrstuvwxyz234567';
