// SPDX-License-Identifier: AGPL-3.0-or-later
//
// WS-S.3.4 — HPKE invite-bootstrap tests.  The interop vector below was SEALED
// by `@hpke/core` (an independent, audited RFC 9180 implementation) for the
// suite DHKEM(X25519,HKDF-SHA256)/HKDF-SHA256/AES-128-GCM (RFC 9180 A.1); this
// runtime's hand-rolled `openBase` must recover the plaintext byte-for-byte,
// pinning the decap + key-schedule + AEAD path to a real HPKE implementation.
// The remaining tests cover self round-trip, the invite seal/open surface,
// wrong-recipient / tamper rejection, and the §10.3 fragment-only URL rule.
import { describe, expect, it } from 'vitest';
import { canonical } from '../crypto/canonical.js';
import {
  buildInviteUrl,
  generateRecipientKeyPair,
  HpkeError,
  INVITE_INFO_LABEL,
  importRecipientPrivateScalar,
  openBase,
  openInvite,
  sealBase,
  sealInvite,
  x25519Pkcs8FromScalar,
} from '../crypto/hpke.js';
import { concatBytes, toBase64Url, utf8 } from '../crypto/runtime.js';
import type { InviteSecret } from '../schemas/invite.js';

function hex(s: string): Uint8Array {
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = Number.parseInt(s.slice(i * 2, i * 2 + 2), 16);
  return out;
}

// Generated by @hpke/core (independent RFC 9180, suite A.1) — see the WS-S.3.4
// scratch generation. The recipient key is ours (we know its scalar); @hpke/core
// performed the SEAL, so opening it proves cross-implementation conformance.
const INTEROP = {
  scalar: '10ac69482cd2d88a5d09565097e7d0fd08ea2dd417890cc880a306007737c361',
  pubRaw: '2ef282584eebf227629a17a9548c3dfcf2455ad823617bfe6300bb2b1d1f0864',
  info: '6c6963696f2e707269766174652e696e766974652e7631',
  aad: '',
  pt: '696e766974652d7365637265742d626f6f7473747261702d7061796c6f6164',
  enc: '27e17947a2c055d12cb93531f1960b8414e034fcffb34d5788ceefb3c711e65c',
  ct: '62750e7797ac255f8cfcb3ca07488cbfcb45bbc13754cfe263062632518849ad44a0c95a6e61e81946d9d249c0cdec',
};

describe('HPKE base-mode RFC 9180 conformance (suite A.1)', () => {
  it('opens a ciphertext sealed by @hpke/core (cross-implementation)', async () => {
    const recipientPrivate = await importRecipientPrivateScalar(hex(INTEROP.scalar));
    const pt = await openBase(
      hex(INTEROP.enc),
      recipientPrivate,
      hex(INTEROP.pubRaw),
      hex(INTEROP.info),
      hex(INTEROP.aad),
      hex(INTEROP.ct),
    );
    expect(new TextDecoder().decode(pt)).toBe('invite-secret-bootstrap-payload');
  });

  it('confirms the info label matches the pinned domain string', () => {
    expect(new TextDecoder().decode(hex(INTEROP.info))).toBe(INVITE_INFO_LABEL);
  });

  it('self round-trips sealBase → openBase', async () => {
    const recipient = await generateRecipientKeyPair();
    const pt = utf8('a short bootstrap message');
    const sealed = await sealBase(recipient.publicKey, utf8('ctx'), new Uint8Array(0), pt);
    expect(sealed.enc).toHaveLength(32);
    const opened = await openBase(
      sealed.enc,
      recipient.privateKey,
      recipient.publicKey,
      utf8('ctx'),
      new Uint8Array(0),
      sealed.ciphertext,
    );
    expect(new TextDecoder().decode(opened)).toBe('a short bootstrap message');
  });

  it('fails closed when the recipient is wrong', async () => {
    const recipient = await generateRecipientKeyPair();
    const other = await generateRecipientKeyPair();
    const sealed = await sealBase(recipient.publicKey, utf8('ctx'), new Uint8Array(0), utf8('m'));
    await expect(
      openBase(
        sealed.enc,
        other.privateKey,
        other.publicKey,
        utf8('ctx'),
        new Uint8Array(0),
        sealed.ciphertext,
      ),
    ).rejects.toMatchObject({ reason: 'open_failed' });
  });

  it('fails closed on a tampered ciphertext or mismatched info', async () => {
    const recipient = await generateRecipientKeyPair();
    const sealed = await sealBase(recipient.publicKey, utf8('ctx'), new Uint8Array(0), utf8('m'));
    const tampered = sealed.ciphertext.slice();
    tampered[0] = (tampered[0] as number) ^ 0xff;
    await expect(
      openBase(
        sealed.enc,
        recipient.privateKey,
        recipient.publicKey,
        utf8('ctx'),
        new Uint8Array(0),
        tampered,
      ),
    ).rejects.toMatchObject({ reason: 'open_failed' });
    await expect(
      openBase(
        sealed.enc,
        recipient.privateKey,
        recipient.publicKey,
        utf8('other'),
        new Uint8Array(0),
        sealed.ciphertext,
      ),
    ).rejects.toMatchObject({ reason: 'open_failed' });
  });

  it('rejects a wrong-length scalar / encapsulated key', async () => {
    expect(() => x25519Pkcs8FromScalar(new Uint8Array(16))).toThrow(RangeError);
    const recipient = await generateRecipientKeyPair();
    await expect(
      openBase(
        new Uint8Array(8),
        recipient.privateKey,
        recipient.publicKey,
        utf8('c'),
        new Uint8Array(0),
        new Uint8Array(40),
      ),
    ).rejects.toMatchObject({ reason: 'malformed_sealed_invite' });
  });
});

describe('invite seal / open (§10.3, §12.2)', () => {
  function invite(): InviteSecret {
    return {
      schema: 'licio.private.invite_secret.v1',
      room_stub_ref: 'stub-123',
      room_public_key: 'cm9vbS1wdWJsaWMta2V5',
      invite_id: 'invite-abc',
      invite_secret: 'aW52aXRlLXNlY3JldA',
      expires_at: '2026-07-01T00:00:00Z',
      max_uses: 5,
      granted_role: 'member',
      requires_admin_approval: true,
    };
  }

  it('round-trips an InviteSecretV1 to the intended recipient', async () => {
    const recipient = await generateRecipientKeyPair();
    const sealed = await sealInvite(recipient.publicKey, invite());
    const opened = await openInvite(recipient.privateKey, recipient.publicKey, sealed);
    expect(opened).toStrictEqual(invite());
  });

  it('authenticates every invite field — a tampered sealed blob fails to open', async () => {
    const recipient = await generateRecipientKeyPair();
    const sealed = await sealInvite(recipient.publicKey, invite());
    // flip a byte in the middle of the base64url ciphertext region
    const chars = sealed.split('');
    const mid = Math.floor(chars.length / 2);
    chars[mid] = chars[mid] === 'A' ? 'B' : 'A';
    await expect(
      openInvite(recipient.privateKey, recipient.publicKey, chars.join('')),
    ).rejects.toBeInstanceOf(HpkeError);
  });

  it('only the intended recipient can open the invite', async () => {
    const recipient = await generateRecipientKeyPair();
    const attacker = await generateRecipientKeyPair();
    const sealed = await sealInvite(recipient.publicKey, invite());
    await expect(openInvite(attacker.privateKey, attacker.publicKey, sealed)).rejects.toMatchObject(
      { reason: 'open_failed' },
    );
  });

  it('rejects a too-short sealed invite', async () => {
    const recipient = await generateRecipientKeyPair();
    await expect(
      openInvite(recipient.privateKey, recipient.publicKey, 'AAAA'),
    ).rejects.toMatchObject({
      reason: 'malformed_sealed_invite',
    });
  });

  it('rejects a sealed payload that is valid canonical but not an InviteSecret', async () => {
    const recipient = await generateRecipientKeyPair();
    const payload = canonical({ schema: 'not.an.invite', stray: 1 });
    const sealed = await sealBase(
      recipient.publicKey,
      utf8(INVITE_INFO_LABEL),
      new Uint8Array(0),
      payload,
    );
    const wire = toBase64Url(concatBytes(sealed.enc, sealed.ciphertext));
    await expect(openInvite(recipient.privateKey, recipient.publicKey, wire)).rejects.toMatchObject(
      {
        reason: 'invalid_invite_payload',
      },
    );
  });

  it('rejects a sealed payload that is not canonical bytes', async () => {
    const recipient = await generateRecipientKeyPair();
    const sealed = await sealBase(
      recipient.publicKey,
      utf8(INVITE_INFO_LABEL),
      new Uint8Array(0),
      Uint8Array.of(0xff, 0xff, 0xff),
    );
    const wire = toBase64Url(concatBytes(sealed.enc, sealed.ciphertext));
    await expect(openInvite(recipient.privateKey, recipient.publicKey, wire)).rejects.toMatchObject(
      {
        reason: 'invalid_invite_payload',
      },
    );
  });
});

describe('invite URL (§10.3 fragment-only)', () => {
  it('places the sealed secret in the fragment, never the path or query', () => {
    const url = buildInviteUrl('https://licio.app/private/join', 'c2VhbGVkLWludml0ZQ');
    expect(url).toBe('https://licio.app/private/join#invite=c2VhbGVkLWludml0ZQ');
    const parsed = new URL(url);
    expect(parsed.pathname).toBe('/private/join');
    expect(parsed.search).toBe('');
    expect(parsed.hash).toContain('c2VhbGVkLWludml0ZQ');
  });

  it('refuses to build a URL that already carries a fragment', () => {
    expect(() => buildInviteUrl('https://licio.app/x#frag', 'abc')).toThrow();
  });
});
