// SPDX-License-Identifier: AGPL-3.0-or-later
//
// AI provenance label (WS-K shared conventions, SPEC §24.1/§24.3). Renders the
// persistent, visible provenance badge every AI-produced artifact carries —
// machine-generated (summaries), AI-classified (topics), AI-draft (claims),
// AI-translated (translations) — and the human-revision upgrades (user-edited,
// steward-confirmed, steward-corrected). A `steward-corrected` artifact is
// visibly distinct from a `machine-generated` one. The label vocabulary is the
// single source of truth from @licio/ai-governance, so UI and metadata never
// drift.
import { type AiProvenanceLabel, isMachineGenerated } from '@licio/ai-governance';
import type { BadgeTone } from '../ui/Badge/index.js';
import { Badge } from '../ui/Badge/index.js';
import type { IconName } from '../ui/Icon/index.js';

interface LabelPresentation {
  text: string;
  tone: BadgeTone;
  icon: IconName;
  /** The accessible explanation of what the label means. */
  description: string;
}

const PRESENTATION: Readonly<Record<AiProvenanceLabel, LabelPresentation>> = {
  'machine-generated': {
    text: 'Machine-generated',
    tone: 'info',
    icon: 'document-check',
    description: 'This content was generated by AI and is never final — a person can revise it.',
  },
  'AI-classified': {
    text: 'AI-classified',
    tone: 'info',
    icon: 'layers',
    description: 'These topic labels were assigned by AI and can be corrected.',
  },
  'AI-draft': {
    text: 'AI draft',
    tone: 'info',
    icon: 'pencil',
    description: 'This claim was drafted by AI and has not been reviewed by a person.',
  },
  'AI-translated': {
    text: 'AI-translated',
    tone: 'info',
    icon: 'globe',
    description: 'This is an AI translation; the original text is always available.',
  },
  'user-edited': {
    text: 'User-edited',
    tone: 'neutral',
    icon: 'user',
    description: 'A person has edited this AI output.',
  },
  'steward-confirmed': {
    text: 'Steward-confirmed',
    tone: 'success',
    icon: 'check-badge',
    description: 'A steward has reviewed and confirmed this AI output.',
  },
  'steward-corrected': {
    text: 'Steward-corrected',
    tone: 'success',
    icon: 'check-badge',
    description: 'A steward has corrected this AI output; it is no longer machine-generated.',
  },
};

export interface AiLabelProps {
  label: AiProvenanceLabel;
  /** Show only the icon (the text stays available to assistive tech). */
  iconOnly?: boolean;
  className?: string;
}

/** The persistent provenance badge for an AI artifact (WS-K, DoD item 5). */
export function AiLabel({ label, iconOnly = false, className }: AiLabelProps): React.ReactElement {
  const presentation = PRESENTATION[label];
  return (
    <Badge
      tone={presentation.tone}
      icon={presentation.icon}
      iconOnly={iconOnly}
      {...(className ? { className } : {})}
    >
      {/* Visible text + a hover title; the full provenance explanation is read
          by assistive tech via the visually-hidden description, so meaning never
          rests on colour alone. */}
      <span title={presentation.description}>
        {presentation.text}
        <span className="sr-only">. {presentation.description}</span>
      </span>
    </Badge>
  );
}

/** Whether a label denotes an AI-origin (not human-revised) artifact. */
export { isMachineGenerated };
