// SPDX-License-Identifier: AGPL-3.0-or-later

/* eslint-disable */

// @ts-nocheck

// biome-ignore-all lint: generated file

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivateRouteImport } from './routes/private'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComplianceConsoleRouteImport } from './routes/compliance-console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateIndexRouteImport } from './routes/private.index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads_.$threadId'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms_.$roomId'
import { Route as ProfileWalletRouteImport } from './routes/profile_.wallet'
import { Route as ProfileSignalLedgerRouteImport } from './routes/profile_.signal-ledger'
import { Route as ProfileSettingsRouteImport } from './routes/profile_.settings'
import { Route as ProfileSecurityRouteImport } from './routes/profile_.security'
import { Route as ProfileSavedRouteImport } from './routes/profile_.saved'
import { Route as ProfileSafetyRouteImport } from './routes/profile_.safety'
import { Route as ProfilePrivacyRouteImport } from './routes/profile_.privacy'
import { Route as ProfileOfflineRouteImport } from './routes/profile_.offline'
import { Route as ProfileNoticesRouteImport } from './routes/profile_.notices'
import { Route as ProfileModeRouteImport } from './routes/profile_.mode'
import { Route as PrivateRoomIdRouteImport } from './routes/private_.$roomId'
import { Route as PrivateMigrateRouteImport } from './routes/private.migrate'
import { Route as DevSimulatorRouteImport } from './routes/dev.simulator'
import { Route as StoriesStoryIdCommentsRouteImport } from './routes/stories.$storyId_.comments'
import { Route as RoomsRoomIdGovernanceRouteImport } from './routes/rooms_.$roomId_.governance'
import { Route as StoriesStoryIdDebateDebateIdRouteImport } from './routes/stories.$storyId.debate.$debateId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceConsoleRoute = ComplianceConsoleRouteImport.update({
  id: '/compliance-console',
  path: '/compliance-console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads_/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms_/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWalletRoute = ProfileWalletRouteImport.update({
  id: '/profile_/wallet',
  path: '/profile/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSignalLedgerRoute = ProfileSignalLedgerRouteImport.update({
  id: '/profile_/signal-ledger',
  path: '/profile/signal-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile_/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/profile_/security',
  path: '/profile/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSavedRoute = ProfileSavedRouteImport.update({
  id: '/profile_/saved',
  path: '/profile/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSafetyRoute = ProfileSafetyRouteImport.update({
  id: '/profile_/safety',
  path: '/profile/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/profile_/privacy',
  path: '/profile/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOfflineRoute = ProfileOfflineRouteImport.update({
  id: '/profile_/offline',
  path: '/profile/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNoticesRoute = ProfileNoticesRouteImport.update({
  id: '/profile_/notices',
  path: '/profile/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileModeRoute = ProfileModeRouteImport.update({
  id: '/profile_/mode',
  path: '/profile/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoomIdRoute = PrivateRoomIdRouteImport.update({
  id: '/private_/$roomId',
  path: '/private/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateMigrateRoute = PrivateMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => PrivateRoute,
} as any)
const DevSimulatorRoute = DevSimulatorRouteImport.update({
  id: '/dev/simulator',
  path: '/dev/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdCommentsRoute = StoriesStoryIdCommentsRouteImport.update({
  id: '/stories/$storyId_/comments',
  path: '/stories/$storyId/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdGovernanceRoute = RoomsRoomIdGovernanceRouteImport.update({
  id: '/rooms_/$roomId_/governance',
  path: '/rooms/$roomId/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdDebateDebateIdRoute =
  StoriesStoryIdDebateDebateIdRouteImport.update({
    id: '/debate/$debateId',
    path: '/debate/$debateId',
    getParentRoute: () => StoriesStoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance-console': typeof ComplianceConsoleRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/private': typeof PrivateRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/styleguide': typeof StyleguideRoute
  '/submit': typeof SubmitRoute
  '/support': typeof SupportRoute
  '/dev/simulator': typeof DevSimulatorRoute
  '/private/migrate': typeof PrivateMigrateRoute
  '/private/$roomId': typeof PrivateRoomIdRoute
  '/profile/mode': typeof ProfileModeRoute
  '/profile/notices': typeof ProfileNoticesRoute
  '/profile/offline': typeof ProfileOfflineRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/safety': typeof ProfileSafetyRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/signal-ledger': typeof ProfileSignalLedgerRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRouteWithChildren
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/private/': typeof PrivateIndexRoute
  '/rooms/$roomId/governance': typeof RoomsRoomIdGovernanceRoute
  '/stories/$storyId/comments': typeof StoriesStoryIdCommentsRoute
  '/stories/$storyId/debate/$debateId': typeof StoriesStoryIdDebateDebateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance-console': typeof ComplianceConsoleRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/styleguide': typeof StyleguideRoute
  '/submit': typeof SubmitRoute
  '/support': typeof SupportRoute
  '/dev/simulator': typeof DevSimulatorRoute
  '/private/migrate': typeof PrivateMigrateRoute
  '/private/$roomId': typeof PrivateRoomIdRoute
  '/profile/mode': typeof ProfileModeRoute
  '/profile/notices': typeof ProfileNoticesRoute
  '/profile/offline': typeof ProfileOfflineRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/safety': typeof ProfileSafetyRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/signal-ledger': typeof ProfileSignalLedgerRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRouteWithChildren
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/private': typeof PrivateIndexRoute
  '/rooms/$roomId/governance': typeof RoomsRoomIdGovernanceRoute
  '/stories/$storyId/comments': typeof StoriesStoryIdCommentsRoute
  '/stories/$storyId/debate/$debateId': typeof StoriesStoryIdDebateDebateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance-console': typeof ComplianceConsoleRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/private': typeof PrivateRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/styleguide': typeof StyleguideRoute
  '/submit': typeof SubmitRoute
  '/support': typeof SupportRoute
  '/dev/simulator': typeof DevSimulatorRoute
  '/private/migrate': typeof PrivateMigrateRoute
  '/private_/$roomId': typeof PrivateRoomIdRoute
  '/profile_/mode': typeof ProfileModeRoute
  '/profile_/notices': typeof ProfileNoticesRoute
  '/profile_/offline': typeof ProfileOfflineRoute
  '/profile_/privacy': typeof ProfilePrivacyRoute
  '/profile_/safety': typeof ProfileSafetyRoute
  '/profile_/saved': typeof ProfileSavedRoute
  '/profile_/security': typeof ProfileSecurityRoute
  '/profile_/settings': typeof ProfileSettingsRoute
  '/profile_/signal-ledger': typeof ProfileSignalLedgerRoute
  '/profile_/wallet': typeof ProfileWalletRoute
  '/rooms_/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRouteWithChildren
  '/threads_/$threadId': typeof ThreadsThreadIdRoute
  '/private/': typeof PrivateIndexRoute
  '/rooms_/$roomId_/governance': typeof RoomsRoomIdGovernanceRoute
  '/stories/$storyId_/comments': typeof StoriesStoryIdCommentsRoute
  '/stories/$storyId/debate/$debateId': typeof StoriesStoryIdDebateDebateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance-console'
    | '/login'
    | '/moderation'
    | '/private'
    | '/profile'
    | '/rooms'
    | '/styleguide'
    | '/submit'
    | '/support'
    | '/dev/simulator'
    | '/private/migrate'
    | '/private/$roomId'
    | '/profile/mode'
    | '/profile/notices'
    | '/profile/offline'
    | '/profile/privacy'
    | '/profile/safety'
    | '/profile/saved'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/signal-ledger'
    | '/profile/wallet'
    | '/rooms/$roomId'
    | '/stories/$storyId'
    | '/threads/$threadId'
    | '/private/'
    | '/rooms/$roomId/governance'
    | '/stories/$storyId/comments'
    | '/stories/$storyId/debate/$debateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance-console'
    | '/login'
    | '/moderation'
    | '/profile'
    | '/rooms'
    | '/styleguide'
    | '/submit'
    | '/support'
    | '/dev/simulator'
    | '/private/migrate'
    | '/private/$roomId'
    | '/profile/mode'
    | '/profile/notices'
    | '/profile/offline'
    | '/profile/privacy'
    | '/profile/safety'
    | '/profile/saved'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/signal-ledger'
    | '/profile/wallet'
    | '/rooms/$roomId'
    | '/stories/$storyId'
    | '/threads/$threadId'
    | '/private'
    | '/rooms/$roomId/governance'
    | '/stories/$storyId/comments'
    | '/stories/$storyId/debate/$debateId'
  id:
    | '__root__'
    | '/'
    | '/compliance-console'
    | '/login'
    | '/moderation'
    | '/private'
    | '/profile'
    | '/rooms'
    | '/styleguide'
    | '/submit'
    | '/support'
    | '/dev/simulator'
    | '/private/migrate'
    | '/private_/$roomId'
    | '/profile_/mode'
    | '/profile_/notices'
    | '/profile_/offline'
    | '/profile_/privacy'
    | '/profile_/safety'
    | '/profile_/saved'
    | '/profile_/security'
    | '/profile_/settings'
    | '/profile_/signal-ledger'
    | '/profile_/wallet'
    | '/rooms_/$roomId'
    | '/stories/$storyId'
    | '/threads_/$threadId'
    | '/private/'
    | '/rooms_/$roomId_/governance'
    | '/stories/$storyId_/comments'
    | '/stories/$storyId/debate/$debateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceConsoleRoute: typeof ComplianceConsoleRoute
  LoginRoute: typeof LoginRoute
  ModerationRoute: typeof ModerationRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RoomsRoute: typeof RoomsRoute
  StyleguideRoute: typeof StyleguideRoute
  SubmitRoute: typeof SubmitRoute
  SupportRoute: typeof SupportRoute
  DevSimulatorRoute: typeof DevSimulatorRoute
  PrivateRoomIdRoute: typeof PrivateRoomIdRoute
  ProfileModeRoute: typeof ProfileModeRoute
  ProfileNoticesRoute: typeof ProfileNoticesRoute
  ProfileOfflineRoute: typeof ProfileOfflineRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfileSafetyRoute: typeof ProfileSafetyRoute
  ProfileSavedRoute: typeof ProfileSavedRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSignalLedgerRoute: typeof ProfileSignalLedgerRoute
  ProfileWalletRoute: typeof ProfileWalletRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRouteWithChildren
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  RoomsRoomIdGovernanceRoute: typeof RoomsRoomIdGovernanceRoute
  StoriesStoryIdCommentsRoute: typeof StoriesStoryIdCommentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-console': {
      id: '/compliance-console'
      path: '/compliance-console'
      fullPath: '/compliance-console'
      preLoaderRoute: typeof ComplianceConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/': {
      id: '/private/'
      path: '/'
      fullPath: '/private/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/threads_/$threadId': {
      id: '/threads_/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms_/$roomId': {
      id: '/rooms_/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/wallet': {
      id: '/profile_/wallet'
      path: '/profile/wallet'
      fullPath: '/profile/wallet'
      preLoaderRoute: typeof ProfileWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/signal-ledger': {
      id: '/profile_/signal-ledger'
      path: '/profile/signal-ledger'
      fullPath: '/profile/signal-ledger'
      preLoaderRoute: typeof ProfileSignalLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/settings': {
      id: '/profile_/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/security': {
      id: '/profile_/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/saved': {
      id: '/profile_/saved'
      path: '/profile/saved'
      fullPath: '/profile/saved'
      preLoaderRoute: typeof ProfileSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/safety': {
      id: '/profile_/safety'
      path: '/profile/safety'
      fullPath: '/profile/safety'
      preLoaderRoute: typeof ProfileSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/privacy': {
      id: '/profile_/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/offline': {
      id: '/profile_/offline'
      path: '/profile/offline'
      fullPath: '/profile/offline'
      preLoaderRoute: typeof ProfileOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/notices': {
      id: '/profile_/notices'
      path: '/profile/notices'
      fullPath: '/profile/notices'
      preLoaderRoute: typeof ProfileNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/mode': {
      id: '/profile_/mode'
      path: '/profile/mode'
      fullPath: '/profile/mode'
      preLoaderRoute: typeof ProfileModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private_/$roomId': {
      id: '/private_/$roomId'
      path: '/private/$roomId'
      fullPath: '/private/$roomId'
      preLoaderRoute: typeof PrivateRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/migrate': {
      id: '/private/migrate'
      path: '/migrate'
      fullPath: '/private/migrate'
      preLoaderRoute: typeof PrivateMigrateRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/dev/simulator': {
      id: '/dev/simulator'
      path: '/dev/simulator'
      fullPath: '/dev/simulator'
      preLoaderRoute: typeof DevSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId_/comments': {
      id: '/stories/$storyId_/comments'
      path: '/stories/$storyId/comments'
      fullPath: '/stories/$storyId/comments'
      preLoaderRoute: typeof StoriesStoryIdCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms_/$roomId_/governance': {
      id: '/rooms_/$roomId_/governance'
      path: '/rooms/$roomId/governance'
      fullPath: '/rooms/$roomId/governance'
      preLoaderRoute: typeof RoomsRoomIdGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/debate/$debateId': {
      id: '/stories/$storyId/debate/$debateId'
      path: '/debate/$debateId'
      fullPath: '/stories/$storyId/debate/$debateId'
      preLoaderRoute: typeof StoriesStoryIdDebateDebateIdRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateMigrateRoute: typeof PrivateMigrateRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateMigrateRoute: PrivateMigrateRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface StoriesStoryIdRouteChildren {
  StoriesStoryIdDebateDebateIdRoute: typeof StoriesStoryIdDebateDebateIdRoute
}

const StoriesStoryIdRouteChildren: StoriesStoryIdRouteChildren = {
  StoriesStoryIdDebateDebateIdRoute: StoriesStoryIdDebateDebateIdRoute,
}

const StoriesStoryIdRouteWithChildren = StoriesStoryIdRoute._addFileChildren(
  StoriesStoryIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceConsoleRoute: ComplianceConsoleRoute,
  LoginRoute: LoginRoute,
  ModerationRoute: ModerationRoute,
  PrivateRoute: PrivateRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RoomsRoute: RoomsRoute,
  StyleguideRoute: StyleguideRoute,
  SubmitRoute: SubmitRoute,
  SupportRoute: SupportRoute,
  DevSimulatorRoute: DevSimulatorRoute,
  PrivateRoomIdRoute: PrivateRoomIdRoute,
  ProfileModeRoute: ProfileModeRoute,
  ProfileNoticesRoute: ProfileNoticesRoute,
  ProfileOfflineRoute: ProfileOfflineRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfileSafetyRoute: ProfileSafetyRoute,
  ProfileSavedRoute: ProfileSavedRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSignalLedgerRoute: ProfileSignalLedgerRoute,
  ProfileWalletRoute: ProfileWalletRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  StoriesStoryIdRoute: StoriesStoryIdRouteWithChildren,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  RoomsRoomIdGovernanceRoute: RoomsRoomIdGovernanceRoute,
  StoriesStoryIdCommentsRoute: StoriesStoryIdCommentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
