// SPDX-License-Identifier: AGPL-3.0-or-later

/* eslint-disable */

// @ts-nocheck

// biome-ignore-all lint: generated file

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads_.$threadId'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms_.$roomId'
import { Route as ProfileWalletRouteImport } from './routes/profile_.wallet'
import { Route as ProfileSignalLedgerRouteImport } from './routes/profile_.signal-ledger'
import { Route as ProfileSettingsRouteImport } from './routes/profile_.settings'
import { Route as ProfileSecurityRouteImport } from './routes/profile_.security'
import { Route as ProfileSavedRouteImport } from './routes/profile_.saved'
import { Route as ProfileSafetyRouteImport } from './routes/profile_.safety'
import { Route as ProfilePrivacyRouteImport } from './routes/profile_.privacy'
import { Route as ProfileNoticesRouteImport } from './routes/profile_.notices'
import { Route as StoriesStoryIdCommentsRouteImport } from './routes/stories.$storyId_.comments'
import { Route as RoomsRoomIdGovernanceRouteImport } from './routes/rooms_.$roomId_.governance'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads_/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms_/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWalletRoute = ProfileWalletRouteImport.update({
  id: '/profile_/wallet',
  path: '/profile/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSignalLedgerRoute = ProfileSignalLedgerRouteImport.update({
  id: '/profile_/signal-ledger',
  path: '/profile/signal-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile_/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/profile_/security',
  path: '/profile/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSavedRoute = ProfileSavedRouteImport.update({
  id: '/profile_/saved',
  path: '/profile/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSafetyRoute = ProfileSafetyRouteImport.update({
  id: '/profile_/safety',
  path: '/profile/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/profile_/privacy',
  path: '/profile/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNoticesRoute = ProfileNoticesRouteImport.update({
  id: '/profile_/notices',
  path: '/profile/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdCommentsRoute = StoriesStoryIdCommentsRouteImport.update({
  id: '/stories/$storyId_/comments',
  path: '/stories/$storyId/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdGovernanceRoute = RoomsRoomIdGovernanceRouteImport.update({
  id: '/rooms_/$roomId_/governance',
  path: '/rooms/$roomId/governance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/styleguide': typeof StyleguideRoute
  '/submit': typeof SubmitRoute
  '/support': typeof SupportRoute
  '/profile/notices': typeof ProfileNoticesRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/safety': typeof ProfileSafetyRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/signal-ledger': typeof ProfileSignalLedgerRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/rooms/$roomId/governance': typeof RoomsRoomIdGovernanceRoute
  '/stories/$storyId/comments': typeof StoriesStoryIdCommentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/styleguide': typeof StyleguideRoute
  '/submit': typeof SubmitRoute
  '/support': typeof SupportRoute
  '/profile/notices': typeof ProfileNoticesRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/safety': typeof ProfileSafetyRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/signal-ledger': typeof ProfileSignalLedgerRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/rooms/$roomId/governance': typeof RoomsRoomIdGovernanceRoute
  '/stories/$storyId/comments': typeof StoriesStoryIdCommentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/styleguide': typeof StyleguideRoute
  '/submit': typeof SubmitRoute
  '/support': typeof SupportRoute
  '/profile_/notices': typeof ProfileNoticesRoute
  '/profile_/privacy': typeof ProfilePrivacyRoute
  '/profile_/safety': typeof ProfileSafetyRoute
  '/profile_/saved': typeof ProfileSavedRoute
  '/profile_/security': typeof ProfileSecurityRoute
  '/profile_/settings': typeof ProfileSettingsRoute
  '/profile_/signal-ledger': typeof ProfileSignalLedgerRoute
  '/profile_/wallet': typeof ProfileWalletRoute
  '/rooms_/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/threads_/$threadId': typeof ThreadsThreadIdRoute
  '/rooms_/$roomId_/governance': typeof RoomsRoomIdGovernanceRoute
  '/stories/$storyId_/comments': typeof StoriesStoryIdCommentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/moderation'
    | '/profile'
    | '/rooms'
    | '/styleguide'
    | '/submit'
    | '/support'
    | '/profile/notices'
    | '/profile/privacy'
    | '/profile/safety'
    | '/profile/saved'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/signal-ledger'
    | '/profile/wallet'
    | '/rooms/$roomId'
    | '/stories/$storyId'
    | '/threads/$threadId'
    | '/rooms/$roomId/governance'
    | '/stories/$storyId/comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/moderation'
    | '/profile'
    | '/rooms'
    | '/styleguide'
    | '/submit'
    | '/support'
    | '/profile/notices'
    | '/profile/privacy'
    | '/profile/safety'
    | '/profile/saved'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/signal-ledger'
    | '/profile/wallet'
    | '/rooms/$roomId'
    | '/stories/$storyId'
    | '/threads/$threadId'
    | '/rooms/$roomId/governance'
    | '/stories/$storyId/comments'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/moderation'
    | '/profile'
    | '/rooms'
    | '/styleguide'
    | '/submit'
    | '/support'
    | '/profile_/notices'
    | '/profile_/privacy'
    | '/profile_/safety'
    | '/profile_/saved'
    | '/profile_/security'
    | '/profile_/settings'
    | '/profile_/signal-ledger'
    | '/profile_/wallet'
    | '/rooms_/$roomId'
    | '/stories/$storyId'
    | '/threads_/$threadId'
    | '/rooms_/$roomId_/governance'
    | '/stories/$storyId_/comments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ModerationRoute: typeof ModerationRoute
  ProfileRoute: typeof ProfileRoute
  RoomsRoute: typeof RoomsRoute
  StyleguideRoute: typeof StyleguideRoute
  SubmitRoute: typeof SubmitRoute
  SupportRoute: typeof SupportRoute
  ProfileNoticesRoute: typeof ProfileNoticesRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfileSafetyRoute: typeof ProfileSafetyRoute
  ProfileSavedRoute: typeof ProfileSavedRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSignalLedgerRoute: typeof ProfileSignalLedgerRoute
  ProfileWalletRoute: typeof ProfileWalletRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  RoomsRoomIdGovernanceRoute: typeof RoomsRoomIdGovernanceRoute
  StoriesStoryIdCommentsRoute: typeof StoriesStoryIdCommentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads_/$threadId': {
      id: '/threads_/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms_/$roomId': {
      id: '/rooms_/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/wallet': {
      id: '/profile_/wallet'
      path: '/profile/wallet'
      fullPath: '/profile/wallet'
      preLoaderRoute: typeof ProfileWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/signal-ledger': {
      id: '/profile_/signal-ledger'
      path: '/profile/signal-ledger'
      fullPath: '/profile/signal-ledger'
      preLoaderRoute: typeof ProfileSignalLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/settings': {
      id: '/profile_/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/security': {
      id: '/profile_/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/saved': {
      id: '/profile_/saved'
      path: '/profile/saved'
      fullPath: '/profile/saved'
      preLoaderRoute: typeof ProfileSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/safety': {
      id: '/profile_/safety'
      path: '/profile/safety'
      fullPath: '/profile/safety'
      preLoaderRoute: typeof ProfileSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/privacy': {
      id: '/profile_/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/notices': {
      id: '/profile_/notices'
      path: '/profile/notices'
      fullPath: '/profile/notices'
      preLoaderRoute: typeof ProfileNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId_/comments': {
      id: '/stories/$storyId_/comments'
      path: '/stories/$storyId/comments'
      fullPath: '/stories/$storyId/comments'
      preLoaderRoute: typeof StoriesStoryIdCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms_/$roomId_/governance': {
      id: '/rooms_/$roomId_/governance'
      path: '/rooms/$roomId/governance'
      fullPath: '/rooms/$roomId/governance'
      preLoaderRoute: typeof RoomsRoomIdGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ModerationRoute: ModerationRoute,
  ProfileRoute: ProfileRoute,
  RoomsRoute: RoomsRoute,
  StyleguideRoute: StyleguideRoute,
  SubmitRoute: SubmitRoute,
  SupportRoute: SupportRoute,
  ProfileNoticesRoute: ProfileNoticesRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfileSafetyRoute: ProfileSafetyRoute,
  ProfileSavedRoute: ProfileSavedRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSignalLedgerRoute: ProfileSignalLedgerRoute,
  ProfileWalletRoute: ProfileWalletRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  RoomsRoomIdGovernanceRoute: RoomsRoomIdGovernanceRoute,
  StoriesStoryIdCommentsRoute: StoriesStoryIdCommentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
