// SPDX-License-Identifier: AGPL-3.0-or-later
//
// One valid sample event per registered topic (WS-E.1.1g test fixtures). Each
// fixture must round-trip through its topic schema unchanged; the registry test
// derives completeness and classification assertions from this map, so adding a
// topic without a fixture fails loudly.
import type { EventTopic } from '../schemas/events/registry.js';

const U1 = '11111111-1111-4111-8111-111111111111';
const U2 = '22222222-2222-4222-8222-222222222222';
const U3 = '33333333-3333-4333-8333-333333333333';
const U4 = '44444444-4444-4444-8444-444444444444';
const T0 = '2026-06-10T10:00:00.000Z';

const base = (eventType: string): Record<string, unknown> => ({
  event_id: U1,
  event_type: eventType,
  timestamp: T0,
  schema_version: '1',
});

export const EVENT_FIXTURES: Readonly<Record<EventTopic, Record<string, unknown>>> = {
  'content.submitted': {
    ...base('content.submitted'),
    story_id: U2,
    submitted_by: U3,
    submission_type: 'link',
    canonical_url: 'https://example.org/report',
    topic_ids: ['water', 'infrastructure'],
    room_id: U4,
    visibility: 'public',
    privacy_classification: 'public',
    retention_tier: 'public_contribution',
  },
  'content.normalized': {
    ...base('content.normalized'),
    story_id: U2,
    submitted_by: U3,
    submission_type: 'link',
    canonical_url: 'https://example.org/report',
    topic_ids: ['water'],
    room_id: U4,
    visibility: 'public',
    source_id: U4,
    language: 'en',
    sensitivity_labels: [],
    duplicate_group_id: null,
    claim_ids: [U1],
    embedding_ref: null,
    privacy_classification: 'public',
    retention_tier: 'public_contribution',
  },
  'content.visibility.changed': {
    ...base('content.visibility.changed'),
    story_id: U2,
    room_id: U3,
    from: 'public',
    to: 'room_only',
    trigger: 'author',
    actor_ref: U4,
    privacy_classification: 'public',
    retention_tier: 'public_contribution',
  },
  'source.opened.aggregate': {
    ...base('source.opened.aggregate'),
    nonce: U4,
    user_id: U3,
    privacy_level: 'standard',
    story_id: U2,
    source_id: U1,
    dwell_bucket: 'moderate',
    bounce: false,
    privacy_classification: 'aggregated',
    retention_tier: 'attention_aggregated',
  },
  'content.saved': {
    ...base('content.saved'),
    nonce: U4,
    user_id: U3,
    privacy_level: 'standard',
    story_id: U2,
    privacy_classification: 'aggregated',
    retention_tier: 'attention_aggregated',
  },
  'attention.aggregate': {
    ...base('attention.aggregate'),
    nonce: U4,
    user_id: U3,
    privacy_level: 'standard',
    session_bucket: '2026-06-10T10:00:00.000Z',
    items: [
      {
        story_id: U2,
        active_dwell_bucket: 'medium',
        source_opened: true,
        context_opened: false,
        reply_depth_bucket: 'shallow',
        return_visit_count_bucket: 'none',
      },
    ],
    privacy_classification: 'aggregated',
    retention_tier: 'attention_aggregated',
  },
  'contribution.created': {
    ...base('contribution.created'),
    contribution_id: U2,
    thread_id: U3,
    user_id: U4,
    contribution_type: 'question',
    target_claim_id: null,
    parent_contribution_id: null,
    has_citation: false,
    accusation_flag: false,
    privacy_classification: 'public',
    retention_tier: 'public_contribution',
  },
  'claim.updated': {
    ...base('claim.updated'),
    claim_id: U2,
    story_id: U3,
    old_status: 'unverified',
    new_status: 'supported',
    updated_by: 'system',
    privacy_classification: 'public',
    retention_tier: 'public_contribution',
  },
  'thread.state.changed': {
    ...base('thread.state.changed'),
    thread_id: U2,
    story_id: U3,
    state_dimension: 'safety',
    old_state: 'normal',
    new_state: 'frozen',
    changed_by: 'system',
    privacy_classification: 'sensitive',
    retention_tier: 'ranking_log',
  },
  'moderation.case.created': {
    ...base('moderation.case.created'),
    case_id: U2,
    target_type: 'contribution',
    target_id: U3,
    reporter_id: U4,
    reason_code: 'MOD_HARASS_002',
    severity: 'high',
    source: 'integrity_review',
    privacy_classification: 'restricted',
    retention_tier: 'moderation_legal',
  },
  'integrity.signal.detected': {
    ...base('integrity.signal.detected'),
    signal_type: 'coordinated_burst',
    target_ids: [U2],
    confidence: 0.8,
    evidence_summary: 'volume 40 exceeded conditioned base rate 6 with 9 distinct actors',
    privacy_classification: 'restricted',
    retention_tier: 'security_log',
  },
  'invariant.run.completed': {
    ...base('invariant.run.completed'),
    invariant_type: 'PWAtt',
    target_type: 'story',
    target_id: U2,
    time_window: '2026-06-10T10:00:00.000Z/1h',
    version: 'v0',
    score_vector: { active_attention: 0.4, participation: 0.2 },
    confidence: 0.7,
    computation_time_ms: 12,
    privacy_classification: 'sensitive',
    retention_tier: 'ranking_log',
  },
  'ranking.decision.logged': {
    ...base('ranking.decision.logged'),
    decision_id: U2,
    story_id: U3,
    context: 'feed',
    score: 0.5,
    position: 3,
    signals_used: ['freshness'],
    explanation_summary: 'Shown for freshness within followed topics.',
    privacy_classification: 'sensitive',
    retention_tier: 'ranking_log',
  },
  'notification.sent': {
    ...base('notification.sent'),
    notification_id: U2,
    user_id: U3,
    notification_type: 'thread_update',
    channel: 'push',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'privacy.request.created': {
    ...base('privacy.request.created'),
    request_type: 'export',
    user_id: U2,
    status: 'received',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'wallet.link.requested': {
    ...base('wallet.link.requested'),
    user_id: U2,
    chain_id: 1,
    wallet_type: 'eoa',
    privacy_classification: 'restricted',
    retention_tier: 'account_active',
  },
  'wallet.linked': {
    ...base('wallet.linked'),
    user_id: U2,
    wallet_ref: 'a'.repeat(64),
    chain_id: 1,
    wallet_type: 'eoa',
    privacy_classification: 'restricted',
    retention_tier: 'account_active',
  },
  'payment.intent.created': {
    ...base('payment.intent.created'),
    payment_intent_id: U2,
    user_id: U3,
    room_id: null,
    target_type: 'bounty',
    target_id: U4,
    asset: 'USDC',
    amount: '2500000',
    jurisdiction_state: 'allowed',
    privacy_classification: 'restricted',
    retention_tier: 'security_log',
  },
  'payment.intent.failed': {
    ...base('payment.intent.failed'),
    payment_intent_id: U2,
    user_id: U3,
    failure_code: 'expired',
    privacy_classification: 'restricted',
    retention_tier: 'security_log',
  },
  'payment.receipt.indexed': {
    ...base('payment.receipt.indexed'),
    payment_intent_id: U2,
    receipt_ref: 'b'.repeat(64),
    chain_id: 1,
    tx_ref: 'c'.repeat(64),
    privacy_classification: 'restricted',
    retention_tier: 'security_log',
  },
  'room.governance.mode.changed': {
    ...base('room.governance.mode.changed'),
    room_id: U2,
    old_mode: 'simulation',
    new_mode: 'testnet',
    changed_by: 'system',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'governance.proposal.created': {
    ...base('governance.proposal.created'),
    proposal_id: U2,
    room_id: U3,
    proposer_user_id: U4,
    proposal_type: 'grant',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'governance.signature.recorded': {
    ...base('governance.signature.recorded'),
    signature_id: U2,
    proposal_id: U3,
    user_id: U4,
    signature_type: 'approve',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'governance.proposal.executed': {
    ...base('governance.proposal.executed'),
    proposal_id: U2,
    room_id: U3,
    execution_state: 'executed',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'governance.proposal.challenged': {
    ...base('governance.proposal.challenged'),
    proposal_id: U2,
    room_id: U3,
    challenge_state: 'open',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'treasury.deposit.indexed': {
    ...base('treasury.deposit.indexed'),
    treasury_id: U2,
    room_id: U3,
    asset: 'ETH',
    amount: '1000000000000000000',
    tx_ref: 'd'.repeat(64),
    privacy_classification: 'restricted',
    retention_tier: 'security_log',
  },
  'treasury.grant.approved': {
    ...base('treasury.grant.approved'),
    grant_id: U2,
    room_id: U3,
    proposal_id: U4,
    asset: 'USDC',
    amount: '50000000',
    privacy_classification: 'restricted',
    retention_tier: 'security_log',
  },
  'treasury.payout.executed': {
    ...base('treasury.payout.executed'),
    grant_id: U2,
    treasury_id: U3,
    payout_state: 'executed',
    tx_ref: 'e'.repeat(64),
    privacy_classification: 'restricted',
    retention_tier: 'security_log',
  },
  'knomosis.action.preflighted': {
    ...base('knomosis.action.preflighted'),
    action_record_id: U2,
    action_type: 'treasury_payout',
    room_id: U3,
    preflight_state: 'passed',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'knomosis.action.submitted': {
    ...base('knomosis.action.submitted'),
    action_record_id: U2,
    action_type: 'treasury_payout',
    submission_state: 'submitted',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'knomosis.event.indexed': {
    ...base('knomosis.event.indexed'),
    deployment_id: U2,
    chain_id: 1,
    block_number: 19_000_000,
    onchain_event_type: 'GrantExecuted',
    reorg_state: 'confirmed',
    privacy_classification: 'sensitive',
    retention_tier: 'account_active',
  },
  'compliance.financial.case.created': {
    ...base('compliance.financial.case.created'),
    case_id: U2,
    trigger_type: 'suspicious_pattern',
    subject_ref: 'f'.repeat(64),
    risk_level: 'high',
    privacy_classification: 'restricted',
    retention_tier: 'moderation_legal',
  },
  'jurisdiction.feature.disabled': {
    ...base('jurisdiction.feature.disabled'),
    policy_id: U2,
    country_or_region: 'EU',
    feature: 'payments',
    privacy_classification: 'sensitive',
    retention_tier: 'security_log',
  },
};
