// SPDX-License-Identifier: AGPL-3.0-or-later
//
// MFCI tests (WS-H.3): table/margin correctness, Markov-basis margin
// preservation + fiber connectivity (brute force), sampler validity
// (nonnegative integer tables sharing margins, acceptance-rate sanity),
// the add-one estimator, score ordering, cheap statistics with null
// calibrations, risk states, and identifier-free summaries.
import { describe, expect, it } from 'vitest';
import {
  type AxisDef,
  addOnePValue,
  analystCaseSummary,
  appealSummary,
  applyMove,
  buildNullCalibration,
  buildSparseTable,
  cellKey,
  computeMargins,
  coordinationStatistic,
  DEFAULT_MFCI_RISK_THRESHOLDS,
  describeMargins,
  effectiveSampleSize,
  enumerateBasisMoves,
  enumerateFiber,
  fiberTest,
  flatten2Way,
  mfciFromPValue,
  moderatorEffectForState,
  type NullCalibration,
  nextRiskState,
  rankingEffectForState,
  riskStateForScore,
  type SparseTable,
  sameMargins,
  sampleFiber,
  subsetSwapMove,
  synchronyScore,
  tableSignature,
  targetConcentrationScore,
  validateMfciRiskThresholds,
} from '../mfci/index.js';

const AXES_2D: AxisDef[] = [
  { name: 'user_group', labels: ['g1', 'g2'] },
  { name: 'target', labels: ['x', 'y'] },
];

const AXES_5D: AxisDef[] = [
  { name: 'user_group', labels: ['g1', 'g2'] },
  { name: 'topic', labels: ['t1', 't2'] },
  { name: 'time_bucket', labels: ['b1', 'b2'] },
  { name: 'action_type', labels: ['report', 'reply'] },
  { name: 'target', labels: ['x', 'y'] },
];

function table5d(observations: string[][]): SparseTable {
  return buildSparseTable(
    AXES_5D,
    observations.map((labels) => ({ labels })),
  );
}

describe('MFCI contingency tables and margins (WS-H.3.2a/b)', () => {
  it('builds the expected sparse table and margins from observations', () => {
    const table = buildSparseTable(AXES_2D, [
      { labels: ['g1', 'x'], count: 3 },
      { labels: ['g1', 'y'] },
      { labels: ['g2', 'y'], count: 2 },
    ]);
    expect(table.total).toBe(6);
    expect(table.cells.get(cellKey([0, 0]))).toBe(3);
    expect(computeMargins(table)).toEqual([
      [4, 2],
      [3, 3],
    ]);
    expect(describeMargins(table).axes).toEqual(['user_group', 'target']);
  });

  it('rejects unknown labels and invalid counts', () => {
    expect(() => buildSparseTable(AXES_2D, [{ labels: ['g1', 'zz'] }])).toThrow(/unknown label/);
    expect(() => buildSparseTable(AXES_2D, [{ labels: ['g1', 'x'], count: -1 }])).toThrow(
      /nonnegative integer/,
    );
  });

  it('flatten2Way sums over the remaining axes', () => {
    const table = table5d([
      ['g1', 't1', 'b1', 'report', 'x'],
      ['g1', 't2', 'b2', 'reply', 'x'],
      ['g2', 't1', 'b1', 'report', 'y'],
    ]);
    const groupTarget = flatten2Way(table, 0, 4);
    expect(groupTarget.get('0,0')).toBe(2); // g1 → x via two different cells
    expect(groupTarget.get('1,1')).toBe(1);
  });
});

describe('MFCI Markov basis (WS-H.3.3a)', () => {
  it('every move preserves all margins when applied', () => {
    const table = table5d([
      ['g1', 't1', 'b1', 'report', 'x'],
      ['g2', 't2', 'b2', 'reply', 'y'],
      ['g1', 't2', 'b1', 'reply', 'x'],
      ['g2', 't1', 'b2', 'report', 'y'],
    ]);
    const moves = enumerateBasisMoves(AXES_5D.map((a) => a.labels.length));
    let applied = 0;
    for (const move of moves) {
      const next = applyMove(table, move, 1);
      if (next) {
        applied += 1;
        expect(sameMargins(table, next)).toBe(true);
        for (const count of next.cells.values()) {
          expect(Number.isInteger(count)).toBe(true);
          expect(count).toBeGreaterThanOrEqual(0);
        }
      }
    }
    expect(applied).toBeGreaterThan(0);
  });

  it('degenerate subset swaps return null', () => {
    expect(subsetSwapMove([0, 0], [0, 1], 1)).toBeNull(); // u_A = v_A
    expect(subsetSwapMove([0, 0], [1, 0], 2)).toBeNull(); // u_Ac = v_Ac
    expect(subsetSwapMove([0, 0], [1, 1], 1)).not.toBeNull();
  });

  it('basis moves connect the whole fiber (brute-force, 2-way table)', () => {
    const observed = buildSparseTable(AXES_2D, [
      { labels: ['g1', 'x'], count: 2 },
      { labels: ['g1', 'y'], count: 1 },
      { labels: ['g2', 'x'], count: 1 },
      { labels: ['g2', 'y'], count: 2 },
    ]);
    const fiber = enumerateFiber(AXES_2D, computeMargins(observed));
    expect(fiber.length).toBeGreaterThan(1);
    const signatures = new Set(fiber.map(tableSignature));
    // BFS over the fiber graph generated by the basis moves.
    const moves = enumerateBasisMoves(AXES_2D.map((a) => a.labels.length));
    const visited = new Set<string>([tableSignature(observed)]);
    const queue: SparseTable[] = [observed];
    while (queue.length > 0) {
      const current = queue.shift();
      if (!current) break;
      for (const move of moves) {
        for (const direction of [1, -1] as const) {
          const next = applyMove(current, move, direction);
          if (!next) continue;
          const sig = tableSignature(next);
          if (!visited.has(sig)) {
            visited.add(sig);
            queue.push(next);
          }
        }
      }
    }
    expect(visited).toEqual(signatures);
  });

  it('basis moves connect a 3-axis fiber too (brute force)', () => {
    const axes: AxisDef[] = [
      { name: 'user_group', labels: ['g1', 'g2'] },
      { name: 'action_type', labels: ['a', 'b'] },
      { name: 'target', labels: ['x', 'y'] },
    ];
    const observed = buildSparseTable(axes, [
      { labels: ['g1', 'a', 'x'], count: 2 },
      { labels: ['g2', 'b', 'y'], count: 2 },
      { labels: ['g1', 'b', 'y'] },
      { labels: ['g2', 'a', 'x'] },
    ]);
    const fiber = enumerateFiber(axes, computeMargins(observed));
    const moves = enumerateBasisMoves(axes.map((a) => a.labels.length));
    const visited = new Set<string>([tableSignature(observed)]);
    const queue: SparseTable[] = [observed];
    while (queue.length > 0) {
      const current = queue.shift();
      if (!current) break;
      for (const move of moves) {
        for (const direction of [1, -1] as const) {
          const next = applyMove(current, move, direction);
          if (!next) continue;
          const sig = tableSignature(next);
          if (!visited.has(sig)) {
            visited.add(sig);
            queue.push(next);
          }
        }
      }
    }
    expect(visited.size).toBe(fiber.length);
  });
});

describe('MFCI Metropolis–Hastings sampler (WS-H.3.3b)', () => {
  const observed = table5d([
    ...Array.from({ length: 6 }, () => ['g1', 't1', 'b1', 'report', 'x']),
    ['g1', 't2', 'b2', 'reply', 'y'],
    ['g2', 't1', 'b2', 'reply', 'y'],
    ['g2', 't2', 'b1', 'reply', 'x'],
    ['g2', 't2', 'b2', 'report', 'y'],
  ]);

  it('every retained state shares the fixed margins with nonneg integers', () => {
    let checked = 0;
    sampleFiber(
      observed,
      (state) => {
        expect(sameMargins(observed, state)).toBe(true);
        for (const count of state.cells.values()) {
          expect(Number.isInteger(count)).toBe(true);
          expect(count).toBeGreaterThanOrEqual(0);
        }
        checked += 1;
        return 0;
      },
      { samples: 50, burnIn: 50, thinning: 2, seed: 7 },
    );
    expect(checked).toBe(50);
  });

  it('acceptance rate sits in a sane band and runs are seed-deterministic', () => {
    const run = (): ReturnType<typeof sampleFiber> =>
      sampleFiber(observed, (t) => coordinationStatistic(t, 'target_concentration'), {
        samples: 200,
        burnIn: 200,
        thinning: 2,
        seed: 99,
      });
    const a = run();
    const b = run();
    expect(a.statistics).toEqual(b.statistics);
    expect(a.diagnostics.acceptanceRate).toBeGreaterThan(0.001);
    expect(a.diagnostics.acceptanceRate).toBeLessThan(0.9);
  });

  it('the chain moves the statistic (the fiber is explored)', () => {
    const run = sampleFiber(observed, (t) => coordinationStatistic(t, 'target_concentration'), {
      samples: 800,
      burnIn: 800,
      thinning: 2,
      seed: 5,
    });
    expect(new Set(run.statistics).size).toBeGreaterThan(1);
  });

  it('effectiveSampleSize handles short and constant series', () => {
    expect(effectiveSampleSize([1, 1, 1])).toBe(3);
    expect(effectiveSampleSize([5, 5, 5, 5, 5, 5])).toBe(6);
    expect(effectiveSampleSize([1, 2, 1, 2, 1, 2, 1, 2])).toBeGreaterThan(1);
  });
});

describe('MFCI p-value and score (WS-H.3.3c)', () => {
  it('implements the add-one estimator exactly', () => {
    expect(addOnePValue(0, 999)).toBeCloseTo(1 / 1000, 12);
    expect(addOnePValue(99, 99)).toBe(1);
    expect(addOnePValue(4, 95)).toBeCloseTo(5 / 96, 12);
    expect(() => addOnePValue(-1, 10)).toThrow();
    expect(() => addOnePValue(11, 10)).toThrow();
  });

  it('MFCI is finite for all valid inputs including zero exceedances', () => {
    const minimal = addOnePValue(0, 10_000);
    expect(Number.isFinite(mfciFromPValue(minimal))).toBe(true);
    expect(mfciFromPValue(1)).toBe(0);
    expect(() => mfciFromPValue(0)).toThrow();
  });

  it('a planted concentration scores higher than an organic table', () => {
    const concentrated = table5d([
      ...Array.from({ length: 12 }, () => ['g1', 't1', 'b1', 'report', 'x']),
      ['g2', 't2', 'b2', 'reply', 'y'],
      ['g2', 't1', 'b2', 'reply', 'y'],
      ['g1', 't2', 'b2', 'reply', 'y'],
      ['g2', 't2', 'b1', 'reply', 'y'],
    ]);
    const organic = table5d([
      ['g1', 't1', 'b1', 'report', 'x'],
      ['g1', 't2', 'b2', 'reply', 'y'],
      ['g2', 't1', 'b2', 'report', 'y'],
      ['g2', 't2', 'b1', 'reply', 'x'],
      ['g1', 't1', 'b2', 'reply', 'x'],
      ['g2', 't2', 'b2', 'report', 'y'],
      ['g1', 't2', 'b1', 'report', 'x'],
      ['g2', 't1', 'b1', 'reply', 'y'],
      ['g1', 't1', 'b1', 'reply', 'y'],
      ['g2', 't2', 'b2', 'reply', 'x'],
      ['g1', 't2', 'b2', 'report', 'x'],
      ['g2', 't1', 'b1', 'report', 'y'],
      ['g1', 't1', 'b2', 'report', 'y'],
      ['g2', 't2', 'b1', 'report', 'x'],
      ['g1', 't2', 'b1', 'reply', 'y'],
      ['g2', 't1', 'b2', 'reply', 'x'],
    ]);
    const sampler = { samples: 500, burnIn: 500, thinning: 2, seed: 42 } as const;
    const hot = fiberTest(concentrated, 'target_concentration', sampler);
    const cold = fiberTest(organic, 'target_concentration', sampler);
    expect(hot.mfci).toBeGreaterThan(cold.mfci);
    expect(hot.pHat).toBeLessThan(cold.pHat);
    expect(hot.pHat).toBeGreaterThan(0);
  });
});

describe('MFCI cheap statistics (WS-H.3.1a/b)', () => {
  const nowMs = 10_000_000;
  const calibration: NullCalibration = {
    statistic: 'target_concentration',
    version: 'v1',
    computedAtMs: nowMs - 3_600_000,
    buckets: [
      { minVolume: 0, q50: 0.3, q90: 0.5, q99: 0.6, sampleCount: 500 },
      { minVolume: 50, q50: 0.2, q90: 0.35, q99: 0.45, sampleCount: 800 },
    ],
  };

  function actions(
    count: number,
    target: (i: number) => string,
    actor: (i: number) => string,
    at: (i: number) => number,
  ): Array<{ actorRef: string; targetId: string; atMs: number }> {
    return Array.from({ length: count }, (_, i) => ({
      actorRef: actor(i),
      targetId: target(i),
      atMs: at(i),
    }));
  }

  it('concentrated reporting scores high; diffuse activity scores low', () => {
    const concentrated = targetConcentrationScore(
      actions(
        60,
        () => 'victim',
        (i) => `u${i}`,
        (i) => nowMs - i * 1000,
      ),
      calibration,
      { nowMs },
    );
    expect(concentrated.rawValue).toBe(1);
    expect(concentrated.score).toBeGreaterThanOrEqual(1);
    const diffuse = targetConcentrationScore(
      actions(
        60,
        (i) => `t${i % 20}`,
        (i) => `u${i}`,
        (i) => nowMs - i * 1000,
      ),
      calibration,
      { nowMs },
    );
    expect(diffuse.score).toBe(0);
  });

  it('bot-like simultaneity scores high; organic arrival does not', () => {
    const syncCalibration: NullCalibration = {
      ...calibration,
      statistic: 'synchrony',
      buckets: [{ minVolume: 0, q50: 0.2, q90: 0.4, q99: 0.5, sampleCount: 400 }],
    };
    const bots = synchronyScore(
      actions(
        30,
        (i) => `t${i}`,
        (i) => `u${i}`,
        (i) => nowMs - 1000 + (i % 3),
      ),
      syncCalibration,
      { nowMs },
    );
    expect(bots.rawValue).toBeGreaterThan(0.9);
    expect(bots.score).toBeGreaterThan(1);
    const organic = synchronyScore(
      actions(
        30,
        (i) => `t${i}`,
        (i) => `u${i}`,
        (i) => nowMs - i * 600_000,
      ),
      syncCalibration,
      { nowMs },
    );
    expect(organic.score).toBe(0);
    // One fast user alone can never trip synchrony (distinct-actor rule).
    const oneUser = synchronyScore(
      actions(
        30,
        () => 't',
        () => 'same-user',
        (i) => nowMs - i,
      ),
      syncCalibration,
      { nowMs },
    );
    expect(oneUser.rawValue).toBe(0);
  });

  it('stale calibrations flag NULL_CALIBRATION_STALE and halve confidence', () => {
    const stale = targetConcentrationScore(
      actions(
        60,
        () => 'victim',
        (i) => `u${i}`,
        () => nowMs,
      ),
      { ...calibration, computedAtMs: nowMs - 100 * 3_600_000 },
      { nowMs },
    );
    expect(stale.reasonCodes).toContain('NULL_CALIBRATION_STALE');
    const fresh = targetConcentrationScore(
      actions(
        60,
        () => 'victim',
        (i) => `u${i}`,
        () => nowMs,
      ),
      calibration,
      { nowMs },
    );
    expect(stale.confidence).toBeCloseTo(fresh.confidence / 2, 10);
  });

  it('too few actions yields zero score with INSUFFICIENT_COVERAGE', () => {
    const result = targetConcentrationScore(
      actions(
        2,
        () => 'v',
        (i) => `u${i}`,
        () => nowMs,
      ),
      calibration,
      { nowMs },
    );
    expect(result.score).toBe(0);
    expect(result.confidence).toBe(0);
    expect(result.reasonCodes).toContain('INSUFFICIENT_COVERAGE');
  });

  it('buildNullCalibration produces volume-bucketed quantiles', () => {
    const samples = Array.from({ length: 200 }, (_, i) => ({
      volume: i < 100 ? 5 : 100,
      rawValue: (i % 100) / 100,
    }));
    const built = buildNullCalibration('target_concentration', 'v2', nowMs, samples);
    expect(built.buckets.length).toBeGreaterThanOrEqual(2);
    const first = built.buckets[0];
    expect(first?.q50).toBeLessThanOrEqual(first?.q99 ?? 1);
  });
});

describe('MFCI risk states (WS-H.3.4a/WS-H.3.4a-2)', () => {
  it('thresholds map scores to the documented states', () => {
    expect(riskStateForScore(0)).toBe('normal');
    expect(riskStateForScore(3.1)).toBe('elevated');
    expect(riskStateForScore(5.5)).toBe('high');
    expect(riskStateForScore(8)).toBe('severe');
    expect(validateMfciRiskThresholds(DEFAULT_MFCI_RISK_THRESHOLDS)).toBeNull();
    expect(validateMfciRiskThresholds({ elevated: 5, high: 4, severe: 6 })).toMatch(/elevated/);
  });

  it('downward transitions require clearing or analyst override', () => {
    const held = nextRiskState('high', 0.5);
    expect(held.to).toBe('high');
    expect(held.reason).toBe('held_pending_review');
    expect(
      nextRiskState('high', 0.5, DEFAULT_MFCI_RISK_THRESHOLDS, { fiberTestCleared: true }).to,
    ).toBe('normal');
    expect(
      nextRiskState('severe', 3.5, DEFAULT_MFCI_RISK_THRESHOLDS, { analystOverride: true }).to,
    ).toBe('elevated');
    expect(nextRiskState('normal', 8).to).toBe('severe');
  });

  it('effects match the SPEC §8.5 table', () => {
    expect(rankingEffectForState('normal')).toEqual({
      distributionDampening: 1,
      freezeTrendAcceleration: false,
      limitCrossCommunitySpread: false,
    });
    expect(rankingEffectForState('elevated').distributionDampening).toBeLessThan(1);
    expect(rankingEffectForState('high').freezeTrendAcceleration).toBe(true);
    expect(rankingEffectForState('severe').limitCrossCommunitySpread).toBe(true);
    expect(moderatorEffectForState('elevated').passiveMonitoring).toBe(true);
    expect(moderatorEffectForState('high').reviewQueue).toBe(true);
    expect(moderatorEffectForState('severe').immediateIntegrityReview).toBe(true);
  });
});

describe('MFCI summaries (WS-H.3.4b/c)', () => {
  const facts = {
    statistic: 'target_concentration' as const,
    mfci: 6.2,
    pHat: 0.002,
    sampleCount: 10_000,
    riskState: 'high' as const,
    conditionedMargins: ['user_group', 'topic', 'time_bucket', 'action_type', 'target'],
    targetCount: 1,
  };

  it('analyst summary names the statistic, margins, and evidence strength', () => {
    const summary = analystCaseSummary(facts);
    expect(summary).toContain('target_concentration');
    expect(summary).toContain('user_group');
    expect(summary).toContain('6.20');
  });

  it('appeal summary is identifier-free and explains the conditioning (MFCI-5)', () => {
    const summary = appealSummary(facts);
    expect(summary).toMatch(/what normal behavior was accounted for/i);
    expect(summary).not.toMatch(/u\d|user-\d|uuid|victim/i);
    expect(summary).toMatch(/reviewed by a person/);
  });
});
